fix testace model related exception and more error handling
some strange reason mongoose causes unhandled error event when finding testcases:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot use 'in' operator to search for 'verification' in released
    at applyGetters (/opentmi/opentmi/node_modules/mongoose/lib/document.js:2304:21)
    at model.Document.$toObject (/opentmi/opentmi/node_modules/mongoose/lib/document.js:2046:5)
    at model.Document.toJSON (/opentmi/opentmi/node_modules/mongoose/lib/document.js:2334:15)
    at Object.stringify (native)
```